# Résolution de systèmes d'équations linéaires 

## 1. Matrices et numpy

Danse cette partie on va définir les  matrices comme des "arrays" numpy de 2 dimensions et les vecteurs comme des "arrays" de 1 dimension.

Pour commencer on importe numpy : (enlever les commentaires des lignes  et exécuter)

In [1]:
import numpy as np

Création d'une matrice et d'un vecteur (enlever les commentaires des lignes d'affichage et exécuter) :

In [2]:
A = np.array([[1,2],[3,4]])
print(A)
x = np.array([5,6])  
print(x)

[[1 2]
 [3 4]]
[5 6]


Avec reshape on peut donner les dimensions souhaitées à un array, par exemple (enlever les commentaires des lignes d'affichage et exécuter)

In [3]:
B=np.array([5,6,7,8,9,10,11,12,13]).reshape(3,3)
print(B)
y=x.reshape(2,1)  #x comme matrice colonne
print(y)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[5]
 [6]]


On peut aussi créer quelques matrices spéciales directement, par exemple (enlever les commentaires des lignes d'affichage et exécuter)

In [4]:
C=np.zeros((2,2)) #matrices 2x2 de 0 
D=np.ones((3,3))  #matrices 3x3 de 1
I=np.eye(2,2)   #matrice identité 2x2
print("C = ")
print(C)
print("D = ")
print(D)
print("I = ")
print(I)

C = 
[[0. 0.]
 [0. 0.]]
D = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
I = 
[[1. 0.]
 [0. 1.]]


La somme/soustraction et le produit  de matrices sont définies  (enlever les commentaires des lignes d'affichage et exécuter) :

In [5]:
print("A + I= ")
print(A + I)
print("A - I= ")
print(A - I)
print("A x I = ")
print(A @ I)

A + I= 
[[2. 2.]
 [3. 5.]]
A - I= 
[[0. 2.]
 [3. 3.]]
A x I = 
[[1. 2.]
 [3. 4.]]


Attention l'opération * n'est pas le produit de matrices. Elle donne la matrice avec les produits des entrées (enlever les commentaires des lignes d'affichage et exécuter) :  

In [6]:
print("A * I = ")
print(A * I)

A * I = 
[[1. 0.]
 [0. 4.]]


On peut aussi multiplier une matrice avec un vecteur (enlever les commentaires des lignes d'affichage et exécuter) :

In [7]:
print("A = ")
print(A)
print("y = ")
print(y)
print("x = ", x)
print("A x y = " )
print(A@y) # avec y vecteur colonne (la réponse est une colonne)
print("A x x = " )
print(A@x) # avec x vecteur ligne (la réponse est une ligne)

A = 
[[1 2]
 [3 4]]
y = 
[[5]
 [6]]
x =  [5 6]
A x y = 
[[17]
 [39]]
A x x = 
[17 39]


Pour connaître les dimensions d'une matrice on peut utiliser shape, par exemple (enlever les commentaires des lignes d'affichage et exécuter) : 

In [8]:
print(A.shape)

(2, 2)


In [9]:
L = np.arange(0,8).reshape(4,2)
print(L)
print(L.shape) 
print("nombre de lignes n = ", L.shape[0])
print("nombre de lignes m = ", L.shape[1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
nombre de lignes n =  4
nombre de lignes m =  2


Pour avoir accès au coefficient $a_{i,j}$ d'une matrice on utilise la syntaxe A[i,j]. Attention : si la matrice est de taille $n \times m$, les indices  vont de $0$ à $n-1$ pour i et de $0$ à $m-1$ pour $j$  (enlever les commentaires des lignes d'affichage et exécuter) :

In [10]:
print(L[0,0])
print(L[3,1])

n = L.shape[0]
m = L.shape[1]
# on peut parcourir tous les coefficients avec deux boucles for : 
for i in range(0,n):
    for j in range(0,m):
        L[i,j]+=1 # on additionne 1 au coeff i,j de L
        print("coef (", i+1,",",j+1,") de L = ", L[i,j])
    # fin for j
# fin for i
        

0
7
coef ( 1 , 1 ) de L =  1
coef ( 1 , 2 ) de L =  2
coef ( 2 , 1 ) de L =  3
coef ( 2 , 2 ) de L =  4
coef ( 3 , 1 ) de L =  5
coef ( 3 , 2 ) de L =  6
coef ( 4 , 1 ) de L =  7
coef ( 4 , 2 ) de L =  8


Pour récupérer la ligne $i$ (ou la colonne $j$) de una matrice A, on peut utiliser la syntaxe A[i,:] (ou A[:,j]) (enlever les commentaires des lignes d'affichage et exécuter) : 

In [11]:
print(L[0,:])  #1ère ligne de L

[1 2]


In [12]:
print(L[:,1])  #2ème colonne de L (mais donné comme une ligne)

[2 4 6 8]


On peut aussi récupérer une partie de la ligne $i$ ou de la colonne $j$ (enlever les commentaires des lignes d'affichage et exécuter) : 

In [13]:
print(L[0:2,1])  #on récupère les 2 premiers coefficients de la 2ème colonne de L 

[2 4]


Autres fonctions

1. np.prod() calcule le produit des coefficients d'un array 

2. np.dot() calcule le produit scalaire entre deux vecteurs

3. np.diag() extrait la diagonale d'une matrice (ou peut servir à créer une matrice diagonale)

4. np.transpose() calcule la transposée d'une matrice

5. Dans linalg on trouve, entre autres, 

    np.linalg.det() pour calculer le déterminant d'une matrice
    
    np.linalg.norm() pour calculer la norme d'une matrice ou vecteur (par defaut, norme euclidienne pour les vecteurs)
    
    np.linalg.cond() pour calculer le conditionement d'une matrice
    
    np.linalg.solve() pour résoudre un système linéaire Ax=b
    
Exemples (enlever les commentaires des lignes d'affichage et exécuter) :

In [14]:
A=np.array([[1, 0, 2], [2, 1, 1], [0, 1, 2]])
b=np.array([1, 1, 2])
print(A)
print(b)


[[1 0 2]
 [2 1 1]
 [0 1 2]]
[1 1 2]


Exemple : Calcul de la matrice tranposée avec np.transpose

In [15]:
At = np.transpose(A)
print("At = ", At)
bt = np.transpose(b)
print("bt = ", bt)

At =  [[1 2 0]
 [0 1 1]
 [2 1 2]]
bt =  [1 1 2]


Exemple : Calcul du produit des coefficients d'un vecteur

In [16]:
print("prod(b) = ", np.prod(b))

print("vérification : b[0]*b[1]*b[2]= ", b[0]*b[1]*b[2])

prod(b) =  2
vérification : b[0]*b[1]*b[2]=  2


Exemple : Extraction d'une diagonale avec np.diag

In [17]:
#print("diagonale de A = ", np.diag(A))
d = np.diag(A) # on extrait la diagonale principale de A
print(d)
d1 = np.diag(A,1) # on extrait la diagonale a_(i,i+1) de A 
print(d1)
d2 = np.diag(A,2) # on extrait la diagonale a_(i,i+2) de A 
print(d2)

[1 1 2]
[0 1]
[2]


Exemple : Création d'une matrice diagonale avec np.diag

In [18]:
D = np.diag(d) # on crée une matrice diagonale avec np.diag et le vecteur d
print(D)
D1 = np.diag(d,1) # on crée une matrice avec le vecteur d dans la diagonale  a_(i,i+1) de A 
print(D1)

[[1 0 0]
 [0 1 0]
 [0 0 2]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 2]
 [0 0 0 0]]


## Exercice 1 

a) Avec np.ones et np.diag (et sans utiliser np.eye) écrire une fonction pour créer la matrice identité d'ordre $n$. La fonction aura comme argument $n$ (la taille de la matrice)


In [19]:
def identite(n):
    I = np.diag(np.ones(n))
    return I

I = identite(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


b)  Avec np.ones et np.diag écrire une fonction pour créer la matrice tridiagonale carrée d'ordre $n$ suivante

$
   T= \left[\begin{array}{rrrrrr}
           2 & -1 & 0 & \cdots & \cdots & 0 \\
           -1 & 2 & -1 &  0 & \cdots   & 0\\
           0 & -1 & 2 & -1 & 0 & \cdots  \\
             & & \ddots &\ddots &\ddots &  \\
             0 &\cdots &\cdots&  -1 & 2 & -1  \\
           0 &\cdots &\cdots& 0& -1 & 2 &  
         \end{array}\right]%.
$. 

La fonction aura comme argument $n$ (la taille de la matrice)


In [20]:
def tridiagonale(n):
    d = np.ones(n)
    T = 2.*np.diag(d) - np.diag(d[0:n-1],1) - np.diag(d[0:n-1],-1)  
    return T

T = tridiagonale(10)
print(T)

[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]


Exemple : Calcul du déterminant de $A$ et $D$ avec np.linalg.det 

In [21]:
print("det(A) = ", np.linalg.det(A))
#print("det(D) = ", np.linalg.det(D))


det(A) =  5.000000000000001


## Exercice 2 (déterminant d'une matrice diagonale)

En utilisant np.prod et np.diag (et sans utiliser np.linalg.det ni des boucles for), calculer le déterminant de la matrice diagonale $D$ définie ci-dessus. Noter que si $D$ est diagonale alors $det(D) = \Pi_{i=1}^n d_{i,i}$. 

In [22]:
detD = np.prod(np.diag(D))
print("D = ", D)
print("det(D) = ", detD)

D =  [[1 0 0]
 [0 1 0]
 [0 0 2]]
det(D) =  2


Exemple : Produit scalaire avec np.dot

In [23]:
# produit scalaire 
print("(b,b) = ", np.dot(b,b))


(b,b) =  6


Exemple : Norme euclidienne d'un vecteur avec np.linalg.norm et np.dot

In [24]:
# norme du vecteur b 
print("||b|| = ", np.linalg.norm(b))

#calculé avec np.dot 
print("(b,b)^1/2 = ", np.sqrt(np.dot(b,b)))


||b|| =  2.449489742783178
(b,b)^1/2 =  2.449489742783178


Exemple : Solution d'un système linéaire $Ax = b$ avec np.linalg.solve

In [25]:
# solution d'un système linéaire Ax = b avec np.linalg.solve
x=np.linalg.solve(A,b)
print("solution de Ax=b, x= ", x)
print("Ax = ", A@x)

solution de Ax=b, x=  [-0.2  0.8  0.6]
Ax =  [1. 1. 2.]


## Exercice 3

 La matrice de Hilbert $H$ de taille $n$ est définie par 


$\quad  (H)_{ij} = \frac{1}{i+j-1}, \quad 1\leq i,j \leq n.$

Par exemple, pour $n=4$, 
$
   H= \left[\begin{array}{rrrr}
           1 & 1/{2} & 1/{3} & 1/{4} \\
           1/{2} & 1/{3} & 1/{4} & 1/{5} \\
           1/{3} & 1/{4} & 1/{5} & 1/{6} \\
           1/{4} & 1/{5} & 1/{6} & 1/{7} \\
         \end{array}\right]%.
$. 
Ecrire une fonction python pour construire la matrice de Hilbert de taille $n$. 

On pourra compléter la fonction ci-dessous (noter que les indices commencent à 0)

In [26]:
def mathilbert(n):
    H = np.zeros((n,n)) # initialisation avec un matrice nule de taille nxn
    for i in range(0,n): # compléter la paranthèse  
        for j in range(0,n):#... à compléter
            H[i,j] = 1/(i+j+1) # car i,j >= 0, on decale de 1, et (i+1)+(i+j)-1 = i+j+1
    return H

mathilbert(4)

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

b) Est-ce que l'on pourrait écrire une fonction similaire mais avec moins de boucles for ? (essayer ci-dessous)

In [31]:
def mathilbert2(n):
    H = np.zeros((n,n)) 
    for i in range(0,n):
        H[i,:] = 1/np.arange(i+1,n+i+1,1) # on calcule la ligne i de H
    return H
H=mathilbert2(4)
print("H=")
print(H)

print("noter que : ")
print("print(np.arange(1,n+1)) = ", np.arange(1,n+1))
print("1/print(np.arange(1,n+1)) = ", 1/np.arange(1,n+1))

H=
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
noter que : 
print(np.arange(1,n+1)) =  [1 2 3 4]
1/print(np.arange(1,n+1)) =  [1.         0.5        0.33333333 0.25      ]
