# TP 4 partie 5 - Résolution de systèmes d'équations linéaires (suite)




##  Factorisation de Cholesky

Si $A$ est une matrice symétrique et définie positive il est possible de construire une factorisation de la forme 

$\qquad A = L L^T$

où $L$ est une matrice triangulaire inférieure avec tous les coefficients de la diagonale positifs.

Dans le cas $n=2$ on a par identification 

$\qquad \left[
\begin{array}{rr}
a_{11} & a_{12} \\
a_{12} & a_{22} 
\end{array}\right]  = 
\left[
\begin{array}{rr}
\ell_{11} & 0 \\
\ell_{21} & \ell_{22}  
\end{array}\right]  \left[
\begin{array}{rr}
\ell_{11} & \ell_{21} \\
0 & \ell_{22}  
\end{array}\right]=
\left[
\begin{array}{rr}
\ell_{11}^2 & \ell_{11}\ell_{21} \\
\ell_{11}h_{21} & \ell_{21}^2 + \ell_{22}^2  
\end{array}\right]$

d'où  $\ell_{11} = \sqrt{a_{11}}$, $\ell_{21} = a_{12}/\ell_{11}$, $\ell_{22} = \sqrt{a_{22} - \ell_{21}^2}$. 

En généralisant au cas d'une matrice de taille $n$, on obtient l'algorithme suivant


$\quad$$h_{11} = \sqrt{a_{11}}$

$\quad$pour $i=2,...,n$

$\quad\quad$pour $j=1,...,i-1$

$\quad\quad\quad$ $\ell_{ij} = \displaystyle\frac{1}{\ell_{jj}}\left(a_{ij} - \displaystyle\sum_{k=1}^{j-1}\ell_{ik}\ell_{jk}\right)$

$\quad\quad$fin

$\quad\quad$$\ell_{ii} = \sqrt{a_{ii} - \displaystyle\sum_{k=1}^{i-1}\ell_{ik}^2}$


$\quad$fin

$\quad$retourner $L$

### Exercice 1. 

b) Programmer l'algorithme de la décomposition de Cholesky. On pourra compléter la fonction python ci-dessous :

In [3]:
import numpy as np
def cholesky(A): 
    # A matrice carrée symétrique déf positive
    # la 
    dimA = A.shape
    n = dimA[0] 
    L = np.zeros([n,n])#... # initialization L comme matrice nulle
    L[0,0]=np.sqrt(A[0,0]) # initilization L[0,0]
    for i in range(1,n): # boucle  pour i  
        for j in range(0,i): # boucle  pour j :
            L[i,j]=(A[i,j] - np.dot(L[i,0:j],L[j,0:j]))/L[j,j]
        L[i,i]=np.sqrt(A[i,i]-np.dot(L[i,0:i],L[i,0:i]))
    return L

def cholesky2(A): 
    # A matrice carrée symétrique déf positive
    # la 
    dimA = A.shape
    n = dimA[0] 
    L = np.zeros([n,n])#... # initialization L comme matrice nulle
    L[0,0]=np.sqrt(A[0,0]) # initilization L[0,0]
    for i in range(1,n): # boucle  pour i  
        for j in range(0,i): # boucle  pour j :
            L[i,j]=(A[i,j] - np.dot(L[i,range(0,j)],L[j,range(0,j)]))/L[j,j]
        L[i,i]=np.sqrt(A[i,i]-np.dot(L[i,range(0,i)],L[i,range(0,i)]))
    return L


b) Calculer la décomposition de Cholesky de la matrice 


$\quad\quad A = \left[
\begin{array}{rrrr}
4 & 2 &-2 \\
2 & 5 & 5 \\
-2 & 5 & 11
\end{array}\right]$.

Vérifier que $A = LL^t$ 

Rappel : Pour calculer la transposée de $A$ on pourra utiliser la fonction numpy np.transpose().

In [4]:
A=np.array([4,2,-2,2,5,5,-2,5,11],dtype=float).reshape(3,3)

In [5]:
L=cholesky2(A)

print(L)
Lt=np.transpose(L)
print(L@Lt)

[[ 2.  0.  0.]
 [ 1.  2.  0.]
 [-1.  3.  1.]]
[[ 4.  2. -2.]
 [ 2.  5.  5.]
 [-2.  5. 11.]]


### Exercice 2 (extrait TP noté 22-23)

Soit A la matrice d'ordre 3 définie par 

$\quad A = \left[
\begin{array}{rrr}
1 & -1 & 1 \\
-1 & m & m \\
1 & m & m
\end{array}
\right]$

où $m=10^{-3}$. Soit $b=(1,-1,1)$. On considère le systèle $Ax = b$

1) Ecrire, ci-dessous, les tableaux (arrays) numpy avec la matrice $A$ et le vecteur $b$. 
On pourra compléter les instructions ci-dessous :

In [6]:
# compléter les espace marqués avec " ... "
m = 1.e-3;
A = np.array([1, -1, 1, -1, m, m, 1, m, m],dtype=float).reshape(3,3)
b = np.array([1,-1,1],dtype = float)
print("A = ", A)
print("b = ", b)

A =  [[ 1.    -1.     1.   ]
 [-1.     0.001  0.001]
 [ 1.     0.001  0.001]]
b =  [ 1. -1.  1.]


2) Avec solve de numpy, résoudre  ci-dessous le système linéaire $Ax = b$. Garder la solution dans un tableau $x$

In [7]:
# compléter les espace marqués avec " ... "

#calcul solution
x = np.linalg.solve(A,b)
# affichage solution
print("solution solve x = ")
print(x)

solution solve x = 
[1. 0. 0.]


3) On considère le vecteur $c=(1,-1 + 2m,1+2m)$.  Ecrire  ci-dessous le tableau (array) numpy le vecteur $c$ 

In [8]:
# compléter les espace marqués avec " ... "

c = np.array([1,-1+2*m,1+2*m])
# affichage c
print("c = ")
print(c)

c = 
[ 1.    -0.998  1.002]


4) Avec solve de numpy, résoudre  ci-dessous le système linéaire $Ax = c$. Garder la solution dans un tableau $z$

In [9]:
# compléter les espace marqués avec " ... "

z = np.linalg.solve(A,c)
# affichage z
print("solution z = ")
print(z)



solution z = 
[1. 1. 1.]


5) Avec norm de numpy, calculer ci-dessous les erreurs relatives $\displaystyle\frac{\|b-c\|}{\|b\|}$ et $\displaystyle\frac{\|x-z\|}{\|x\|}$. 

In [13]:
# compléter les espace marqués avec " ... "

errb = np.linalg.norm(b-c)/np.linalg.norm(b)
errx = np.linalg.norm(x-z)/np.linalg.norm(x)
print("erreur 2ns membre = ", errb)
print("erreur solution   = ", errx)

erreur 2ns membre =  0.0016329931618554536
erreur solution   =  1.4142135623731444


6) En comparant ces erreurs, que pourrait-on dire sur le conditionnement de la matrice $A$ ? (écrire votre réponse ci-dessous, justifier) 

In [24]:
# l'erreur relative du second membre est petit (~0,1%) mais l'erreur relative de la solution est 
# grande (141%) : la matrice doit etre mal conditionnee, cond(A)>>1

In [23]:
# en effet, calcul du nombre de conditionnement avec numpy : 
print("cond(A) = ", np.linalg.cond(A))

cond(A) =  1000.0000000000034
