# Résolution de systèmes d'équations linéaires (partie 2)



## Exercice 1

a) Construire la matrice de Hilbert pour $n=4$ (voir TP4 partie 1, Exercice 3). Avec np.ones(), construire le vecteur $x= (1,1,1,1)$ puis calculer $b= Hx$. Résoudre, avec np.linalg.solve, le système $Hx = b$. Comparer avec la solution exacte x = (1,1,1,1).

b) Refaire a) avec $n=7$, $n=10$, $n=15$. Pour chaque cas, calculer  l'erreur entre la solution exacte $x$ et la solution calculée par numpy $x_{np}$

$ || x - x_{np} || $ 

où $|| \cdot ||$ corréspond à la norme euclidienne. 



In [42]:
import numpy as np
n=4
def mathilbert(n):
    H = np.zeros((n,n)) # initialisation avec un matrice nule de taille nxn
    for i in range(0,n): # compléter la paranthèse  
        for j in range(0,n):#... à compléter
            H[i,j] = 1/(i+j+1) # car i,j >= 0, on decale de 1, et (i+1)+(i+j)-1 = i+j+1
    return H

H = mathilbert(n) #fonction mathilbert Exercice 3 , TP4 partie 1
x = np.ones(n) # à compléter
# suite de l'exercice...
b = H@x 
print("second membre b = ", b)
xnp = np.linalg.solve(H,b)
print("solution solve numpy de Hx = b : xnp = ", xnp)

second membre b =  [2.08333333 1.28333333 0.95       0.75952381]
solution solve numpy de Hx = b : xnp =  [1. 1. 1. 1.]


b) Refaire a) avec $n=7$, $n=10$, $n=15$. Pour chaque cas, calculer  l'erreur entre la solution exacte $x$ et la solution calculée par numpy $x_{np}$

$ || x - x_{np} || $ 

où $|| \cdot ||$ corréspond à la norme euclidienne. 


In [43]:
for n in [4,7,10,15]:
    H = mathilbert(n) 
    x = np.ones(n) 
    b = H@x 
    print("b = ", b)
    xnp = np.linalg.solve(H,b) 
    print("n = ",n," solution solve numpy : xnp = ", xnp)
    erreur=np.sqrt(np.dot(x-xnp,x-xnp))
    print("n = ",n," erreur ||x-xnp|| = ", erreur)
    erreur=np.linalg.norm(x-xnp)
    print("n = ",n," erreur2 ||x-xnp|| = ", erreur)    

b =  [2.08333333 1.28333333 0.95       0.75952381]
n =  4  solution solve numpy : xnp =  [1. 1. 1. 1.]
n =  4  erreur ||x-xnp|| =  8.274819244860764e-14
n =  4  erreur2 ||x-xnp|| =  8.274819244860764e-14
b =  [2.59285714 1.71785714 1.32896825 1.09563492 0.93654401 0.81987734
 0.73013376]
n =  7  solution solve numpy : xnp =  [1.         1.         1.         1.00000001 0.99999999 1.00000001
 1.        ]
n =  7  erreur ||x-xnp|| =  2.020679983537482e-08
n =  7  erreur2 ||x-xnp|| =  2.020679983537482e-08
b =  [2.92896825 2.01987734 1.60321068 1.34680042 1.16822899 1.03489566
 0.93072899 0.84669538 0.77725094 0.7187714 ]
n =  10  solution solve numpy : xnp =  [1.         0.99999996 1.00000087 0.99999211 1.00003756 0.99989682
 1.00016919 0.99983655 1.00008579 0.99998114]
n =  10  erreur ||x-xnp|| =  0.0002741818135171358
n =  10  erreur2 ||x-xnp|| =  0.0002741818135171358
b =  [3.31822899 2.38072899 1.93955252 1.66177474 1.46440632 1.31440632
 1.1953587  1.09795611 1.01643437 0.94698992 0.

# Résolution de systèmes triangulaires 

## Exercice 2

On veut construire la matrice $n \times n$ triangulaire supérieure suivante 

$\quad  U = \left(\begin{array}{rrrrrr}
              n & n-1 & n-2 & \dots & \dots & 1 \\
              0 &  n & n-1 & n-2 & \dots & 2  \\
              0 & 0 & n  & n-1 &\ddots & 3 \\
              \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
              0 & \dots & \dots & 0 & n & n-1 \\
              0 & \dots & \dots &  \dots & 0 & n  
            \end{array}
\right).
$

Ecrire une fonction python pour construire des matrices de ce type. Utiliser le moins de boucles for possible. 
Tester avec $n=5,10,15$. 

Indication : on pourrait utiliser la fonction np.diag()

In [44]:
def triangulairesup(n):
    U=np.zeros((n,n))
    for i in range(0,n):
        U = U + np.diag((n-i)*np.ones(n-i),i)
    return U

#test avec n=4
n=4
U = triangulairesup(n)
print("n = ", n)
print(U)

# test avec n=10
n=10
U = triangulairesup(n)
print("n = ", n)
print(U)

n =  4
[[4. 3. 2. 1.]
 [0. 4. 3. 2.]
 [0. 0. 4. 3.]
 [0. 0. 0. 4.]]
n =  10
[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
 [ 0. 10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [ 0.  0. 10.  9.  8.  7.  6.  5.  4.  3.]
 [ 0.  0.  0. 10.  9.  8.  7.  6.  5.  4.]
 [ 0.  0.  0.  0. 10.  9.  8.  7.  6.  5.]
 [ 0.  0.  0.  0.  0. 10.  9.  8.  7.  6.]
 [ 0.  0.  0.  0.  0.  0. 10.  9.  8.  7.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.  9.  8.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10.  9.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]


In [45]:
#une autre manière : avec np.arange
def triangulairesup(n):
    U=np.zeros((n,n))
    for i in range(0,n):
        U[i,i:n] = np.arange(n,i,-1) #on remplie les coefficients de la ligne i à partir de la diagonale
    return U

# test de np.arange avec l'argument "-1" : 
print(np.arange(10,2,-1))
# test triangulairesup 
U = triangulairesup(4)
print(U)

[10  9  8  7  6  5  4  3]
[[4. 3. 2. 1.]
 [0. 4. 3. 2.]
 [0. 0. 4. 3.]
 [0. 0. 0. 4.]]


### Résolution de systèmes triangulaires inférieurs (méthode de déscente) 

Soit  $L$ une matrice $n\times n$ triangulaire 
inférieure non-singulière (c.-à-d., $\ell_{ij} = 0$ si $j>i$ et $det(L)\neq 0$). 
Soit $b$ un vecteur de taille $n$. 
Pour résoudre le système $Lx = b$ 
on peut utiliser l'algorithme 
suivant  : 

1. Etant donnés une matrice $L$ (triangulaire inférieure) de taille $n\times n$ et un vecteur $b$ de taille $n$

2. $x_1 = \displaystyle\frac{b_1}{\ell_{11}}$ 

3. pour $i = 2,\dots,n$

$\quad\quad\quad x_i=\displaystyle\frac{1}{\ell_{ii}}\left(b_i 
	  - \displaystyle\sum_{j=1}^{i-1} \ell_{ij}x_j \right)$

$\quad\quad\!\!$fin
  
4. Retourner $x$

## Exercice 3

1) Ecrire  une fonction avec la méthode de descente. La fonction doit vérifier que la matrice $L$ est inversible (par exemple, en calculant le produit des entrées 
de la diagonale principale) et que les dimensions de $L$ et $b$ sont compatibles.   

On pourra compléter la fonction ci-dessous 

In [46]:
def descente(L,b):
    dimL=L.shape
    dimb=b.size # on suppose que b est un array 1d, avec size on récupère sa dimension
    n=dimL[0]   # nombres de lignes de L
    m=dimL[1]   # nombres de colonnes de L 
    if(n != m): # on vérifie si la matrice est carrée
        print("matrice non carrée !")
        return
    # vérifier ici si L et b ont des dimensions compatibles 
    # if(....): # à compléter 
    #    print("dimensions de L et b non compatibles ")
    #    return
    # vérifier ici si la matrice L est sigulière, i.e. det(L)=0 
    #if(...) # à compléter
    #    print("matrice L singulière ")
    #    return
    x=np.zeros(n)  # initialisation vecteur solution
    x[0]=b[0]/L[0,0] # initialisation 
    #for i in ...: # à compléter 
        #x[i] = # à compléter
    return x  # vecteur avec la solution du système

def descente(L,b):
    dimL=L.shape
    dimb=b.size
    n=dimL[0]
    m=dimL[1]
    if(n != m):
        print("matrice non carrée !")
        return
    if(dimb != n):
        print("dimensions de L et b non compatibles ")
        return
    if(np.prod(np.diag(L)) == 0):
        print("matrices L singulière ")
        return
    x=np.zeros(n)
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        x[i] = (b[i] - np.dot(L[i,range(0,i)],x[0:i]))/L[i,i]
    return x

# Remarque : avec np.dot (produit scalaire) on calcule la somme \sum_{j=1}^{i-1} \ell_{ij}x_j 

2. Tester la fonction descente avec le système $Lx = b$ avec 

$\quad  L = \left(\begin{array}{rrr}
           1 & 0 & 0  \\
           2 & 3 & 0  \\
           {4} & {5} & {6} 
         \end{array}\right),\quad\quad b = \left(\begin{array}{r}
            1 \\ 2 \\ 3 
            \end{array}\right) 
$          
Tester les vérifications en modifiant les dimensions de $L$ et $b$ 

In [47]:
L = np.array([[1, 0, 0],[2, 3, 0],[4, 5, 6]], dtype=float)
print(L)
b = np.array([1.,2.,3.])
n=np.shape(L)[0]
print(" nombre de lignes L n = ", n)
np.size(b)
x=descente(L,b)
print("solution calculée x =", x)
print("solution numpy =", np.linalg.solve(L,b))

L = np.array([[1, 0, 0],[2, 3, 0],[4, 5, 6],[7,8,9]], dtype=float)
print(L)
b = np.array([1.,2.,3.])
n=np.shape(L)[0]
print(n)
np.size(b)
x=descente(L,b)
print(x)


L = np.array([[1., 0., 0.],[2., 3., 0.],[4., 5., 0.]])
print(L)
b = np.array([1.,2.,3.])
n=np.shape(L)[0]
print(n)
np.size(b)
x=descente(L,b)
print(x)

L = np.array([[1, 0, 0],[2, 3, 0],[4, 5, 6]], dtype=float)
print(L)
b = np.array([1,2,3,4],dtype=float)
n=np.shape(L)[0]
print("taille matrice = ",n)
print("dim b =", np.size(b))
x=descente(L,b)
print(x)

[[1. 0. 0.]
 [2. 3. 0.]
 [4. 5. 6.]]
 nombre de lignes L n =  3
solution calculée x = [ 1.          0.         -0.16666667]
solution numpy = [ 1.         -0.         -0.16666667]
[[1. 0. 0.]
 [2. 3. 0.]
 [4. 5. 6.]
 [7. 8. 9.]]
4
matrice non carrée !
None
[[1. 0. 0.]
 [2. 3. 0.]
 [4. 5. 0.]]
3
matrices L singulière 
None
[[1. 0. 0.]
 [2. 3. 0.]
 [4. 5. 6.]]
taille matrice =  3
dim b = 4
dimensions de L et b non compatibles 
None


### Résolution de systèmes triangulaires supérieurs (méthode de remontée) 

Soit $U$ 
une matrice $n\times n$ triangulaire 
supérieure non singulière (c.-à-d., $u_{ij} = 0$ si $j<i$ et $det(U)\neq 0$). Soit $b$ un vecteur de taille $n$.  
Pour résoudre le système $Ux = b$ 
on peut utiliser l'algorithme 
suivant : 

1. Etant donnés une matrice $U$ (triangulaire supérieure) de taille $n\times n$ et un vecteur $b$ de taille $n$

2. $x_n = \displaystyle\frac{b_n}{u_{nn}}$

3. pour $i = n-1,\dots,1$

$\quad\quad\quad x_i = \displaystyle\frac{1}{u_{ii}}\left(b_i 
	  - \displaystyle\sum_{j=i+1}^n u_{ij}x_j \right)$

$\quad\quad$fin

4. retourner $x$

## Exercice 4

1. Ecrire  une fonction avec la méthode de rémontée. La fonction doit vérifier que la matrice $U$ est inversible (par exemple, en calculant le produit des entrées 
de la diagonale principale ou le déterminant) et que les dimensions de $U$ et $b$ sont compatibles.   

On pourra compléter la fonction ci-dessous 

In [48]:
def remontee(U,b):
    dimU=U.shape
    dimb=b.size # on suppose que b est un array 1d, avec size on récupère sa dimension
    n=dimU[0]   # nombres de lignes de U
    m=dimU[1]   # nombres de colonnes de U 
    if(n != m): # on vérifie si la matrice est carrée
        print("matrice non carrée !")
        return
    # vérifier ici si L et b ont des dimensions compatibles 
    # if(....): # à compléter 
    #    print("dimensions de L et b non compatibles ")
    #    return
    # vérifier ici si la matrice L est sigulière, i.e. det(L)=0 
    #if(...) # à compléter
    #    print("matrices L singulière ")
    #    return
    x=np.zeros(n)  # initialisation vecteur solution
    x[n-1]=b[n-1]/L[n-1,n-1] # initialisation 
    #for i in ...: # à compléter 
        #x[i] = # à compléter
    return x  # vecteur avec la solution du système

def remontee(U,b):
    dimU=U.shape
    dimb=b.size # on suppose que b est un array 1d, avec size on récupère sa dimension
    n=dimU[0]   # nombres de lignes de U
    m=dimU[1]   # nombres de colonnes de U 
    if(n != m): # on vérifie si la matrice est carrée
        print("matrice non carrée !")
        return
    if(dimb != n):
        print("dimensions de U et b non compatibles ")
        return
    if(np.prod(np.diag(U)) == 0):
        print("matrices U singulière ")
        return
    x=np.zeros(n)
    x[n-1]=b[n-1]/U[n-1,n-1]
    for i in range(n-2,-1,-1):  # i.e. n-2 >= i > -1 et i diminue de 1 à chaque fois (le dernier -1 dans range) (*), 
         x[i] = (b[i] - np.dot(U[i,range(i+1,n)],x[i+1:n]))/U[i,i]
    return x  # vecteur avec la solution du système

# (*) pour l'utilisation de range voir l'exemple ci-dessous 

In [49]:
# exemple boucle for avec i décroissante : 
for i in range(10,-1,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0


2. Tester la fonction avec le système $Ux = b$ où $U = L^T$ avec $L$ et $b$ la matrice et vecteur de l'exercice 3.2.



In [50]:
L = np.array([[1, 0, 0],[2, 3, 0],[4, 5, 6]],dtype=float)
print("L")
print(L)
U = np.transpose(L)
print("U=")
print(U)
b = np.array([1,2,3],dtype=float)
n=np.shape(U)[0]
print(" nombre de lignes U n = ", n)
np.size(b)
x=remontee(U,b)
print("solution calculée x =", x)
print("solution numpy =", np.linalg.solve(U,b))


L
[[1. 0. 0.]
 [2. 3. 0.]
 [4. 5. 6.]]
U=
[[1. 2. 4.]
 [0. 3. 5.]
 [0. 0. 6.]]
 nombre de lignes U n =  3
solution calculée x = [-0.66666667 -0.16666667  0.5       ]
solution numpy = [-0.66666667 -0.16666667  0.5       ]


In [51]:
# Exemple avec un système de taille n=50
U = triangulairesup(50)
print(U)
b = np.ones(50); 
xc=remontee(U,b)
print("solution calculée xc =", xc)
#print("solution exacte x = ", x)
xnp = np.linalg.solve(U,b)
print("solution numpy =", xnp)
print("erreur || xc - xnp || = ", np.sqrt(np.dot(xc-xnp,xc-xnp)))


[[50. 49. 48. ...  3.  2.  1.]
 [ 0. 50. 49. ...  4.  3.  2.]
 [ 0.  0. 50. ...  5.  4.  3.]
 ...
 [ 0.  0.  0. ... 50. 49. 48.]
 [ 0.  0.  0. ...  0. 50. 49.]
 [ 0.  0.  0. ...  0.  0. 50.]]
solution calculée xc = [0.00103483 0.00101454 0.00099464 0.00097514 0.00095602 0.00093728
 0.0009189  0.00090088 0.00088322 0.0008659  0.00084892 0.00083227
 0.00081595 0.00079996 0.00078427 0.00076889 0.00075382 0.00073904
 0.00072454 0.00071034 0.00069641 0.00068275 0.00066937 0.00065624
 0.00064337 0.00063076 0.00061839 0.00060627 0.00059438 0.00058272
 0.0005713  0.0005601  0.00054911 0.00053835 0.00052779 0.00051744
 0.0005073  0.00049735 0.0004876  0.00047804 0.00046866 0.00045947
 0.00045046 0.00044163 0.00043297 0.00042448 0.00041616 0.000408
 0.0004     0.02      ]
solution numpy = [0.00103483 0.00101454 0.00099464 0.00097514 0.00095602 0.00093728
 0.0009189  0.00090088 0.00088322 0.0008659  0.00084892 0.00083227
 0.00081595 0.00079996 0.00078427 0.00076889 0.00075382 0.00073904
 0.000724