## Equations non-linéaires (4)


### Exercice 1

On considère l'équation non-linéaire $f(x) = 0$, avec $f$ une fonction continue. Soit $[a,b]$ un intervalle 

On suppose que la solution $\alpha$ est contenue dans $[a,b]$. 

Soit $q =  \frac{f(b)-f(a)}{b-a}$, sous certaines conditions, la suite 
définie par 

$\quad x_0 = (a+b)/2$, 

$\quad x_{k+1} = x_k - f(x_k)/q,\quad k\ge 0$,

converge vers la solution $\alpha$.

L'algorithme de la méthode de la corde est le suivant

1. Soient 
   $f$ une fonction, 
   [a,b] un intervalle, 
    $\epsilon$ une tolérance, 
   $Nmax$ un nombre maximal d'itérations.

2. Initialisation $k=0$, $err={b-a}$ (compteur d'itérations et  erreur)

3. $q =  \frac{f(b)-f(a)}{b-a}$, $x_0 = \frac{(a+b)}{2}$ 
   

3. tant que $err>tol$ et $k\le Nmax$, faire :
   
   $\quad x_{k+1} = x_k - f(x_k)/q$
   
   $\quad err = |x_{k+1} - x_k| $
   
   $\quad k=k+1$
   
   fin (tant que)

4. afficher  $x_{k}$, $f(x_k)$, $err$ et $k$

5. retourner  $(x_{k})$

1) Ecrire une fonction python avec l'implémentation de la méthode de la corde. La fonction retournera un tableau (array) avec les valeurs des itérés $x_k$. On pourra compléter la fonction ci-dessous :

In [2]:
import numpy as np

def corde(f,a,b,tol,nmax):
    x = []
    xp = (a+b)/2
    x.append(xp)
    err = b-a
    q = (f(b)-f(a))/(b-a)
    k=0
    while err > tol and k <= nmax :
        xn = xp - f(xp)/q
        x.append(xn)
        err = np.abs(xn-xp)
        xp = xn
        k = k+1
    print("fin corde : x = ", xn, " nombre itérations = ", k+1, " erreur = ",err)
    xa = np.asarray(x)
    return xa

2) On considère l'équation non-linéaire $f(x) = x^2 - 2 = 0$ dont la solution est $\alpha = \sqrt{2}$. Programmer la fonction $f$. 

Utiliser la fonction précédente et la fonction avec la méthode de la corde pour calculer un tableau avec les erreurs $e_k = |x_k - \alpha|$, $k=0,1,dots, K$ (où $K$ est la taille du tableau contenant les itérés). Utiliser $a=1$, $b=2$, $tol = 10^{-9}$ et $Nmax=100$. 

In [3]:
def f(x):
    return x**2 - 2

x = corde(f,1,2,1e-9, 100)
alpha = np.sqrt(2)
err = np.abs(x-alpha)
print(err)

fin corde : x =  1.41421356237793  nombre itérations =  9  erreur =  7.970357707165476e-11
[8.57864376e-02 2.45310429e-03 1.38289479e-04 7.90253317e-06
 4.51932629e-07 2.58463919e-08 1.47817958e-09 8.45383763e-11
 4.83479923e-12]


3) Calculer, ci-dessous, un tableau avec les quotients $\displaystyle\frac{e_{k+1}}{e_k}$, $k=0,1,\dots,K-1$. 

In [4]:
print(x)
K=x.size
q1 = err[1:K-1]/err[0:K-2]
print(q1)

[1.5        1.41666667 1.41435185 1.41422146 1.41421401 1.41421359
 1.41421356 1.41421356 1.41421356]
[0.02859548 0.05637326 0.05714486 0.05718832 0.05719081 0.05719095
 0.05719087]


4) Calculer, ci-dessous, un tableau avec les quotients $\displaystyle\frac{e_{k+1}}{e_k^2}$, $k=0,1,\dots, K-1$. 

In [5]:
q2 = err[1:K-1]/(err[0:K-2]**2)
print(q2)

[3.33333333e-01 2.29803752e+01 4.13226389e+02 7.23670790e+03
 1.26547197e+05 2.21272451e+06 3.86900692e+07]


5) D'après les résultats précédents, quel serait l'ordre de la méthode de la corde ? 


### Exercice 2

On considère $A\in \mathbb{R}_+$. On veut calculer une approximation de $\alpha = \sqrt{A}$. Pour cela, on considère la suite définie par 

$\quad x_0$ (point initial, $x_0\neq 0$)

$\quad x_{k+1} = \frac{1}{2}\left(\displaystyle\frac{A}{x_k} + x_k\right),\quad k\ge 0$

On peut montrer que la suite $(x_k)$ converge vers $\alpha$. 
Cette méthode est appellée méthode de déformation d'un rectangle car on peut voir les nombres $x_k$ et $A/x_k$ comme les côtés d'un rectangle $R_k$ de surface $A$. Quand $k\to \infty$ alors $R_k$ tend vers un carré 
de côté $\sqrt{A}$.

On considère, l'algorithme suivant

1. Soient 
   $A$ un nombre réel positif, 
   $x_0$ un point initial, 
    $\epsilon$ une tolérance, 
   $Nmax$ un nombre maximal d'itérations.

2. Initialisation $k=0$, $err=1 + \epsilon$ (compteur d'itérations et  erreur)

   
4. tant que $err>tol$ et $k\le Nmax$, faire :
   
   $\quad x_{k+1} = \frac{1}{2}\left(\displaystyle\frac{A}{x_k} + x_k\right)$
   
   $\quad err = |x_{k+1} - x_k| $
   
   $\quad k=k+1$
   
   fin (tant que)

4. afficher  $(x_{k})$, $f(x_k)$, $err$ et $k$

5. retourner  $(x_{k})$

1) Ecrire une fonction python avec l'implémentation de cet algorithme. La fonction retournera un tableau (array) avec les valeurs des itérés $x_k$. On pourra compléter la fonction ci-dessous :

In [6]:
def deformation_rectangle(A,x0,tol,nmax):
    if A < 0:
        print("A est negatif, stop ")
        return 
    else:
        x = []
        x.append(x0)
        xp = x0
        err = 1.+ tol
        k=0
        while err > tol and k <= nmax :
            xn = 0.5*(A/x[k]+x[k])
            x.append(xn)
            err = np.abs(xn-xp)
            xp = xn
            k=k+1
        print("fin def. rect. : x = ", xn, " nombre itérations = ", k+1, " erreur = ",err)
        xa = np.asarray(x)
        return xa


2) On considère $A=2$ et $\alpha = \sqrt{2}$. 

Utiliser la fonction précédente  pour calculer un tableau avec les erreurs $e_k = |x_k - \alpha|$, $k=0,1,dots, K$ (où $K$ est la taille du tableau contenant les itérés). Utiliser $x0=2$, $tol = 10^{-9}$ et $Nmax=100$. 

In [8]:

x = deformation_rectangle(2,2,1e-9, 100)
alpha = np.sqrt(2)
err = np.abs(x-alpha)
print(err)

fin def. rect. : x =  1.414213562373095  nombre itérations =  6  erreur =  1.5949463971764999e-12
[5.85786438e-01 8.57864376e-02 2.45310429e-03 2.12390141e-06
 1.59472435e-12 2.22044605e-16]


3) Calculer, ci-dessous, un tableau avec les quotients $\displaystyle\frac{e_{k+1}}{e_k}$, $k=0,1,\dots,K-1$. 

In [9]:
print(x)
K=x.size
q1 = err[1:K-1]/err[0:K-2]
print(q1)

[2.         1.5        1.41666667 1.41421569 1.41421356 1.41421356]
[1.46446609e-01 2.85954792e-02 8.65801515e-04 7.50846693e-07]


4) Calculer, ci-dessous, un tableau avec les quotients $\displaystyle\frac{e_{k+1}}{e_k^2}$, $k=0,1,\dots, K-1$. 

In [10]:
q2 = err[1:K-1]/(err[0:K-2]**2)
print(q2)

[0.25       0.33333333 0.35294118 0.35352238]


5) D'après les résultats précédents, quel serait l'ordre de la méthode de déformation du rectangle ? 