# TP 4 Résolution de systèmes d'équations linéaires (partie 3)

##  Méthode de Gauss 

On veut résoudre $Ax = b$ ($A$ matrice 
 $n\times n$ non-singulière, $b,x\in \mathbb{R}^n$). Avec des transformations 
élémentaires et sous certaines conditions sur $A$ on peut transformer 
le système original dans un système équivalent $Ux = \tilde{b}$ avec $U$ une 
matrice triangulaire supérieure.  

Une version de l'algorithme (sans resolution du système) est la suivante : 


$\quad$pour $k=1,...,n-1$

$\quad\quad$ si $|a_{kk}| < \epsilon$ alors  

$\quad\quad\quad$ message d'erreur (pivot nul), sortir

$\quad\quad$pour $i=k+1,...,n$

$\quad\quad\quad$ $m = a_{ik}/a_{kk}$ 

$\quad\quad\quad$ $a_{ik} = 0 $

$\quad\quad\quad$pour $j=k+1,...,n$

$\quad\quad\quad\quad$$a_{ij} = a_{ij} - m \times a_{kj}$

$\quad\quad\quad$fin (boucle $j$)

$\quad\quad\quad$$b_i = b_i - m \times b_k$ 

$\quad\quad$fin (boucle $i$)

$\quad$fin (boucle $k$)


Observations : $\epsilon$ est une valeur petite à fixer (c'est-à-dire, une tolérance, par exemple $10^{-14}$). 
Dans cette version, la matrice $A$ et le vecteur $b$ sont modifiés à chaque étape. 

A la fin de la boucle pour $k$, la matrice $A$ correspondra à $U$ et le vecteur  $b$ à $\tilde{b}$. Une fois l'échelonnement éfectué, on pourra  calculer la solution du système $Ax = b$ en utilisant la méthode de remontée (pour la résolution de systèmes trinagulaires supérieurs). 

### Exercice 1 

a) Programmer une fonction python avec l'algorithme de Gauss ci-dessus. 

In [1]:
import numpy as np


import numpy as np

def gauss(A,b):
    # algorithme de Gauss pour échelonnement de (A|b)
    # avec A matrice nxn et b vecteur de taille n
    tol = 1e-14
    dimA = A.shape
    n=dimA[0]
    m=dimA[1]
    if n!=m: #on vérifie si la matrice est carrée 
        print("matrice non carrèe")
        return
    for k in range(0,n-1): 
        if abs(A[k,k])< tol:
            print("pivot (presque) nul, arrêt", A[k,k])
            return
        for i in range(k+1,n):
            m = A[i,k]/A[k,k]
            A[i,k]=0
            for j in range(k+1,n):
                A[i,j] = A[i,j] - m*A[k,j]
            #fin boucle j
            b[i]=b[i] - m*b[k]
        #fin boucle i
    #fin boucle k        
    return [A,b]
#fin fonction gauss

b) En utilisant la fonction gauss et la fonction avec la méthode de remontée du tp précédent, résoudre
 le système  $Ax = b$ avec : 

$A=\left[
\begin{array}{rrrr}
4 &0 &0  &0\\
-4 &3 &2 &0\\
4 & 0 &2 &1\\
0 &3 &0 &1 
\end{array}\right], \:\:
b=\left[
\begin{array}{r}
10\\
0\\
7\\
6
\end{array}\right].
$

Vérifier les calculs avec les résultats obtenus avec la fonction np.linalg.solve

Observation : utiliser l'option "dtype=float" de np.array pour créer des matrices de nombres flottants (sinon, les matrices pourraient utiliser le type entier "int"), par exemple 



In [21]:
A = np.array([1,2,3,4], dtype=float).reshape(2,2)
print(A)

[[1. 2.]
 [3. 4.]]


In [9]:
import numpy as np

# corrigé fonction remontée 
def remontee(U,b):
    dimU=U.shape
    dimb=b.size # on suppose que b est un array 1d, avec size on récupère sa dimension
    n=dimU[0]   # nombres de lignes de U
    m=dimU[1]   # nombres de colonnes de U 
    if(n != m): # on vérifie si la matrice est carrée
        print("matrice non carrée !")
        return
    # vérifier ici si L et b ont des dimensions compatibles 
    if(n!=dimb): # à compléter 
        print("dimensions de L et b non compatibles ")
        return
    # vérifier ici si la matrice L est sigulière, i.e. det(L)=0 
    if(np.prod(np.diag(U))==0): # à compléter
        print("matrices L singulière ")
        return
    x=np.zeros(n)  # initialisation vecteur solution
    x[n-1]=b[n-1]/U[n-1,n-1] # initialisation 
    for i in range(n-2,-1,-1): 
        x[i] = (b[i] - np.dot(U[i,range(i+1,n)],x[i+1:n]))/U[i,i]
    return x  # vecteur avec la solution du système
#fin remontee
# matrice A
A=np.array([4,0,0,0,-4,3,2,0,4,0,2,1,0,3,0,1],dtype=float).reshape(4,4)
#vecteur b :
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))

print("système échélonné :")
[U,bb]=gauss(A,b)
print("matrice U :")
print(U)
print("vecteur ~b : ")
print(bb)
print("solution avec gauss et remontée : ")
print(remontee(A,b))
print("matrice A : ")

# matrice A : à compléter
#A=np.array([4,0,0,0,-4,3,2,0,4,0,2,1,0,3,0,1],...).reshape(...,...)

#vecteur b :
# b = ....

# solution avec np.linalg.solve : 
# np.linalg.solve()
# ...


matrice A : 
[[ 4.  0.  0.  0.]
 [-4.  3.  2.  0.]
 [ 4.  0.  2.  1.]
 [ 0.  3.  0.  1.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[ 0.25  0.5   0.25 -0.5 ]
système échélonné :
matrice U :
[[4. 0. 0. 0.]
 [0. 3. 2. 0.]
 [0. 0. 2. 1.]
 [0. 0. 0. 2.]]
vecteur ~b : 
[ 1.  2.  0. -1.]
solution avec gauss et remontée : 
[ 0.25  0.5   0.25 -0.5 ]
matrice A : 


c) Refaire les calculs du b) avec les matrices 

$\left[
\begin{array}{rrrr}
6 &2 &1 &-1\\
2 &4 &1 &0\\
1 &1 &4 &-1\\
-1 &0 &-1 &3 
\end{array}\right], \:\: 
\left[
\begin{array}{rrrr}
1 &2 &3 &4\\
2 &2 &3 &4\\
3 &3 &3 &4\\
4 &4 &4 &4 
\end{array}\right]
$


In [4]:
# matrice A
A=np.array([6,2,1,-1,2,4,1,0,1,1,4,-1,-1,0,-1,3],dtype=float).reshape(4,4)
#vecteur b :
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))

print("système échélonné :")
[U,bb]=gauss(A,b)
print("matrice U :")
print(U)
print("vecteur ~b : ")
print(bb)
print("solution avec gauss et remontée : ")
print(remontee(A,b))
print("matrice A : ")



matrice A : 
[[ 6.  2.  1. -1.]
 [ 2.  4.  1.  0.]
 [ 1.  1.  4. -1.]
 [-1.  0. -1.  3.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[0.16753927 0.08900524 0.30890052 0.4921466 ]
système échélonné :
matrice U :
[[ 6.          2.          1.         -1.        ]
 [ 0.          3.33333333  0.66666667  0.33333333]
 [ 0.          0.          3.7        -0.9       ]
 [ 0.          0.          0.          2.58108108]]
vecteur ~b : 
[1.         0.66666667 0.7        1.27027027]
solution avec gauss et remontée : 
[0.16753927 0.08900524 0.30890052 0.4921466 ]
matrice A : 


In [5]:
# matrice A
A=np.array([1,2,3,4,2,2,3,4,3,3,3,4,4,4,4,4],dtype=float).reshape(4,4)
#vecteur b :
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))

print("système échélonné :")
[U,bb]=gauss(A,b)
print("matrice U :")
print(U)
print("vecteur ~b : ")
print(bb)
print("solution avec gauss et remontée : ")
print(remontee(A,b))
print("matrice A : ")

matrice A : 
[[1. 2. 3. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [4. 4. 4. 4.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[0.   0.   0.   0.25]
système échélonné :
matrice U :
[[ 1.          2.          3.          4.        ]
 [ 0.         -2.         -3.         -4.        ]
 [ 0.          0.         -1.5        -2.        ]
 [ 0.          0.          0.         -1.33333333]]
vecteur ~b : 
[ 1.         -1.         -0.5        -0.33333333]
solution avec gauss et remontée : 
[ 0.   -0.   -0.    0.25]
matrice A : 


### Méthode de décomposition LU 

A partir de 
la méthode de Gauss et sous certaines conditions on peut factoriser $A$ comme un produit entre deux matrices : $A=LU$, avec $U$ la matrice triangulaire supérieure obtenue avec la méthode de Gauss, et $L$ une matrice triangulaire inférieure qui contient les multiplicateurs $m_{ij}$.

Dans la  version ci-dessous, la matrice $A$ n'est pas modifiée et les matrices $L$ et $U$ sont calculées séparément : 

$\quad$Initialisation $L=I$, $U=A$ 

$\quad$pour $k=1,...,n-1$  

$\quad$$\quad$ si $|u_{kk}| < \epsilon$ alors  

$\quad$$\quad$$\quad$ message d'erreur (pivot nul), sortir


$\quad$$\quad$pour $i=k+1,...,n$    

$\quad$$\quad$$\quad$$m = u_{ik}/u_{kk}$ 

$\quad$$\quad$$\quad$$\ell_{ik} = m $  

$\quad$$\quad$$\quad$$u_{ik} = 0 $  

$\quad$$\quad$$\quad$pour $j=k+1,...,n$   

$\quad$$\quad$$\quad$$\quad$$u_{ij} = u_{ij} - m \times u_{kj}$ 
                                

$\quad$$\quad$$\quad$fin              

                     
$\quad$$\quad$fin              

$\quad$fin   

$\quad$retourner $L$ et $U$

### Exercice 2. 

a) Programmer ci dessous une fonction python de l'algorithme de factorisation LU ci-dessus. Pour initialiser les matrices $L$ et $U$ on pourra utiliser np.eye (pour créer la matrice identité) et np.copy (pour copier la matrice A), respectivement.


In [6]:
def lu(A):
    tol = 1e-14
    dimA = A.shape
    n=dimA[0]
    m=dimA[1]
    if n!=m:
        print("matrice non carrèe")
        return
    L = np.eye(n) #initialisation L=I (identité)
    U = np.copy(A)#initialisation U=A (copie de A)
    for k in range(0,n-1): 
        if abs(U[k,k])<tol:
            print("pivot (presque) nul, arrêt")
            return
        for i in range(k+1,n):
            m = U[i,k]/U[k,k]
            U[i,k]=0
            L[i,k]=m
            for j in range(k+1,n):
                U[i,j] = U[i,j] - m*U[k,j]
            #fin boucle j
        #fin boucle i
    #fin boucle k        
    return [L,U]
#fin fonction lu



b) Calculer la décomposition LU  des matrices de l'exercice 1 (et vérifier que l'on a $A=LU$) : 

$\left[
\begin{array}{rrrr}
4 &0 &0  &0\\
-4 &3 &2 &0\\
4 & 0 &2 &1\\
0 &3 &0 &1 
\end{array}\right], \:\:
\left[
\begin{array}{rrrr}
6 &2 &1 &-1\\
2 &4 &1 &0\\
1 &1 &4 &-1\\
-1 &0 &-1 &3 
\end{array}\right], \:\: 
\left[
\begin{array}{rrrr}
1 &2 &3 &4\\
2 &2 &3 &4\\
3 &3 &3 &4\\
4 &4 &4 &4 
\end{array}\right]
$

In [7]:
# Calcul décompositions LU
# A = np.array(...)
#...
# matrice A
#A=np.array([4,0,0,0,-4,3,2,0,4,0,2,1,0,3,0,1],dtype=float).reshape(4,4)
A=np.array([6,2,1,-1,2,4,1,0,1,1,4,-1,-1,0,-1,3],dtype=float).reshape(4,4)
#A=np.array([1,2,3,4,2,2,3,4,3,3,3,4,4,4,4,4],dtype=float).reshape(4,4)
print("matrice A : ")
print(A)
[L,U]  = lu(A)
print("matrice L :")
print(L)
print("matrice U :")
print(U)
print("produit L.U :")
print(L@U)

matrice A : 
[[ 6.  2.  1. -1.]
 [ 2.  4.  1.  0.]
 [ 1.  1.  4. -1.]
 [-1.  0. -1.  3.]]
matrice L :
[[ 1.          0.          0.          0.        ]
 [ 0.33333333  1.          0.          0.        ]
 [ 0.16666667  0.2         1.          0.        ]
 [-0.16666667  0.1        -0.24324324  1.        ]]
matrice U :
[[ 6.          2.          1.         -1.        ]
 [ 0.          3.33333333  0.66666667  0.33333333]
 [ 0.          0.          3.7        -0.9       ]
 [ 0.          0.          0.          2.58108108]]
produit L.U :
[[ 6.00000000e+00  2.00000000e+00  1.00000000e+00 -1.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  4.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  5.55111512e-18 -1.00000000e+00  3.00000000e+00]]


### Deuxième version pour la  décomposition LU 


Avec l'algorithme ci-dessous on calcule la décomposition LU en modifiant la matrice A pour garder dans sa partie 
triangulaire inférieure les multiplicateurs $m$ (donc la matrice L) et dans sa partie supérieure la matrice U (Noter que la diagonale de $L$ n'est pas gardé) : 


$\quad$pour $k=1,...,n-1$  

$\quad$$\quad$ si $|a_{kk}| < \epsilon$ alors  

$\quad$$\quad$$\quad$ message d'erreur (pivot nul), sortir


$\quad$$\quad$pour $i=k+1,...,n$    

$\quad$$\quad$$\quad$$m = a_{ik}/a_{kk}$ 

$\quad$$\quad$$\quad$$a_{ik} = m $  

$\quad$$\quad$$\quad$pour $j=k+1,...,n$   

$\quad$$\quad$$\quad$$\quad$$a_{ij} = a_{ij} - m \times a_{kj}$ 
                                

$\quad$$\quad$$\quad$fin              

                     
$\quad$$\quad$fin              

$\quad$fin   

Observations : On peut voir que la matrice $A$ est modifiée à chaque étape.  
A la fin de la boucle pour $k$, la partie triangulaire supérieure (avec la diagonale) 
correspondra à $U$. Aussi, pour éviter l'utilisation d'une autre matrice, 
les multiplicateurs  $m$ sont stockés à la place des entrées 
$a_{ij}$, de la matrice $A$, qui deviennent $0$ à chaque étape. Ainsi, la matrice $L$ (qui a 
une diagonale principale égale à $1$)  correspondra à la partie 
triangulaire inférieure de $A$ (sans la diagonale). 

### Exercice 3

a) Programmer une fonction python avec l'algorithme de factorisation LU ci-dessus. 

In [12]:

def lu2(A):
    # A matrice de taille nxn
    tol = 1e-14
    dimA = A.shape
    n=dimA[0]
    m=dimA[1]
    if n!=m:
        print("matrice non carrèe")
        return
    for k in range(0,n-1): 
        if abs(A[k,k])<tol :
            print("pivot (presque) nul, arrêt")
            return
        for i in range(k+1,n):
            m = A[i,k]/A[k,k]
            A[i,k] = m 
            for j in range(k+1,n):
                A[i,j] = A[i,j] - m*A[k,j]
            #fin boucle j
        #fin boucle i
    #fin boule k            
    return A

b) Tester la fonction en calculant la décomposition LU des matrices des exercices 1 et 2  : 

$\left[
\begin{array}{rrrr}
4 &0 &0  &0\\
-4 &3 &2 &0\\
4 & 0 &2 &1\\
0 &3 &0 &1 
\end{array}\right], \:\:
\left[
\begin{array}{rrrr}
6 &2 &1 &-1\\
2 &4 &1 &0\\
1 &1 &4 &-1\\
-1 &0 &-1 &3 
\end{array}\right], \:\: 
\left[
\begin{array}{rrrr}
1 &2 &3 &4\\
2 &2 &3 &4\\
3 &3 &3 &4\\
4 &4 &4 &4 
\end{array}\right]
$



In [14]:
A=np.array([6,2,1,-1,2,4,1,0,1,1,4,-1,-1,0,-1,3],dtype=float).reshape(4,4)
#A=np.array([1,2,3,4,2,2,3,4,3,3,3,4,4,4,4,4],dtype=float).reshape(4,4)
print("matrice A : ")
print(A)
AA=lu2(A)
print("matrice AA = lu(A) :")
print(AA)
print("mais, en fait, A est modifiée :")
print(A)
print("A= (L|U)")



matrice A : 
[[ 6.  2.  1. -1.]
 [ 2.  4.  1.  0.]
 [ 1.  1.  4. -1.]
 [-1.  0. -1.  3.]]
matrice AA = lu(A) :
[[ 6.          2.          1.         -1.        ]
 [ 0.33333333  3.33333333  0.66666667  0.33333333]
 [ 0.16666667  0.2         3.7        -0.9       ]
 [-0.16666667  0.1        -0.24324324  2.58108108]]
mais, en fait, A est modifiée :
[[ 6.          2.          1.         -1.        ]
 [ 0.33333333  3.33333333  0.66666667  0.33333333]
 [ 0.16666667  0.2         3.7        -0.9       ]
 [-0.16666667  0.1        -0.24324324  2.58108108]]
A= (L|U)


c) Ecrire une fonction python pour résoudre un système $Ax=b$  en utilisant la fonction lu2, et les fonctions remontée et descente du TP précédent. (Si $A=LU$ alors $Ax=b$ est équivalent à $L(Ux)= b$. Si on pose $Ux=y$, alors pour calculer $x$ on peut résoudre d'abord le système $Ly = b$ puis le système $Ux = y$).




In [16]:
# corrigé fonction descente 
def descente(L,b):
    dimL=L.shape
    dimb=b.size
    n=dimL[0]
    m=dimL[1]
    if(n != m):
        print("matrice non carrée !")
        return
    if(dimb != n):
        print("dimensions de L et b non compatibles ")
        return
    if(np.prod(np.diag(L)) == 0):
        print("matrices L singulière ")
        return
    x=np.zeros(n)
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        x[i] = (b[i] - np.dot(L[i,range(0,i)],x[0:i]))/L[i,i]
    return x

#fin descente
  
def resolutionLU(A,b):
    # A matrice nxn
    # b matrice colonne nx1 (ou ligne)
    # a compléter ...
    dimA=A.shape
    n=dimA[0]
    m=dimA[1]  
    lu2(A)
    # on recupère les matrices L et U de A :
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for i in range(0,n):
        U += np.diag(np.diag(A,i),i) 
        if i==0:
            L = np.diag(np.ones(n))
        else :
            L += np.diag(np.diag(A,-i),-i)
    # on résout les systèmes Ly = b et Ux = y
    y=descente(L,b)
    x=remontee(U,y)
    return x




d) Tester la fonction avec les systèmes de l'exercice 1. 


In [17]:
A=np.array([1,2,3,4,2,2,3,4,3,3,3,4,4,4,4,4],dtype=float).reshape(4,4)
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))
print("solution avec LU : ")
print(resolutionLU(A,b))

print("système 2 ")
A=np.array([6,2,1,-1,2,4,1,0,1,1,4,-1,-1,0,-1,3],dtype=float).reshape(4,4)
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))
print("solution avec LU : ")

print(resolutionLU(A,b))

matrice A : 
[[1. 2. 3. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [4. 4. 4. 4.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[0.   0.   0.   0.25]
solution avec LU : 
[ 0.00000000e+00 -0.00000000e+00 -7.40148683e-17  2.50000000e-01]
système 2 
matrice A : 
[[ 6.  2.  1. -1.]
 [ 2.  4.  1.  0.]
 [ 1.  1.  4. -1.]
 [-1.  0. -1.  3.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[0.16753927 0.08900524 0.30890052 0.4921466 ]
solution avec LU : 
[0.16753927 0.08900524 0.30890052 0.4921466 ]


In [24]:
# deuxième version sans construire les matrices L et U explicitement :
# on modifie la fonction descente pour tenir compte du fait que la diagonale de L est égale à 1
# (pas besoin de faire la division /l_ii)

# corrigé fonction descente 
def descente2(L,b):
    # version pour matrice L avec diagonale = 1 (implicite)
    dimL=L.shape
    dimb=b.size
    n=dimL[0]
    m=dimL[1]
    if(n != m):
        print("matrice non carrée !")
        return
    if(dimb != n):
        print("dimensions de L et b non compatibles ")
        return
    if(np.prod(np.diag(L)) == 0):
        print("matrices L singulière ")
        return
    x=np.zeros(n)
    x[0]=b[0]# /L[0,0] # car L[0,0]=1
    for i in range(1,n):
        x[i] = (b[i] - np.dot(L[i,range(0,i)],x[0:i]))# /L[i,i]
    return x

#fin descente
  
def resolutionLU2(A,b):
    # A matrice nxn
    # b matrice colonne nx1 (ou ligne)
    # a compléter ...
    dimA=A.shape
    n=dimA[0]
    m=dimA[1]  
    lu2(A)
    # on résout les systèmes Ly = b et Ux = y
    y=descente2(A,b) # on utilise descente2 
    x=remontee(A,y)
    return x

# l'algorithme en descente2 utilise la partie inférieure de A qui contient L (sans la diagonale)
# l'algorithme en remo utilise la partie supérieure de A qui contient U (avec la diagonale)

In [25]:
A=np.array([1,2,3,4,2,2,3,4,3,3,3,4,4,4,4,4],dtype=float).reshape(4,4)
b=np.array([1., 1., 1., 1.])
print("matrice A : ")
print(A)
print("vecteur b :")
print(b)
print("solution avec np.linalg.solve : ")
print(np.linalg.solve(A,b))
print("solution avec LU : ")
print(resolutionLU2(A,b))


matrice A : 
[[1. 2. 3. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [4. 4. 4. 4.]]
vecteur b :
[1. 1. 1. 1.]
solution avec np.linalg.solve : 
[0.   0.   0.   0.25]
solution avec LU : 
[ 0.00000000e+00 -0.00000000e+00 -7.40148683e-17  2.50000000e-01]


### Exercice Bonus 

Ecrire une fonction python qui effectue la permutation des lignes $k$ et $r$ d'une matrice ou un vecteur. 
Compléter la fonction ci-dessous

In [1]:

def permutation_lignes(A,k,r):
    #version 1
    # on effectue la permutation de lignes k et r de A
    # A matrice de taille n lignes et m colonnes ou vecteur de taille n
    # k,r indices entre 0 et n-1
    # on retourne la matrice (ou vecteur) A modifiée avec la permutation
    # on assume que les indices k et r sont entre 1 et n 
    kk = k-1
    rr = r-1 
    ligneAk = np.copy(A[kk,:])
    A[kk,:] = A[rr,:]
    A[rr,:] = ligneAk
    return A
