In [1]:
#####################################################################
#
# Exécuter chaque cellule avec "shift+enter" ou le bouton ">| Run" 
# dans la barre de menu
#
#####################################################################
# Quelques rappels sur python
#
# les variables ne se déclarent pas, elles sont crées au moment 
# de les affecter avec une valeur
a=1
b=2.0
print("a =", a, " b =", b)

a = 1  b = 2.0


In [2]:
# les types de variables numériques sont int (entier), float (double précision)  et complex (nombre complex)
print(" a est de type ", type(a))
print(" b est de type ", type(b))


 a est de type  <class 'int'>
 b est de type  <class 'float'>


In [5]:
#Opérations élémentaires :
# +, - , * , /  (somme, soustraction, multiplication, division)
print(a+b, a-b, a*b, a/b)

3.0 -1.0 2.0 0.5


In [6]:
# Puissance : **
print(a**b, b**b)

1.0 4.0


In [3]:
# Boucle while : syntax while (condition) : ...
i=1
while i < 10:
    print(i)
    i=i+1
print("fin de la boucle avec i=", i)    
    

1
2
3
4
5
6
7
8
9
fin de la boucle avec i= 10


In [7]:
# boucle for : syntax for x in ... : ...
for i in range(10):
    print(i)


0
1
2
3
4
5
6
7
8
9


In [9]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [10]:
I = [1,3,5,7]
for i in I:
    print(i)

1
3
5
7


In [13]:
for x in range(2, 20, 4):
  print(x) 

2
6
10
14
18


In [14]:
# If ... else : syntax 
# if (condition):
#     ...
# else :
#     ...
#  
# ou (si plus de deux conditions) 
# if (condition):
#     ...
#  elif (condition):
#     ...
#  else:
#      ...
if b>a:
    print("b est plus grand que a")
    

b est plus grand que a


In [4]:
a=3
b=3
if b>a:
    print("b est plus grand que a")
elif b==a:
    print("b est égal à a")
else:
    print("b est plus petit que a")
    

b est égal à a


In [ ]:
#autres conditions 
# <= (plus petit ou égal)
# >= (plus grand ou égal)
# != (différent)

# connecteurs logiques : 'and' et 'or'


In [5]:
# Fonctions : def nomfonction: ... return valeur(s)
def valeurabsolue(a):
    if a>=0:
        rep = a
    else:
        rep = -a
    return rep 
valeurabsolue(-22)

22

In [19]:
valeurabsolue(-2)

2

In [69]:
# Quelques modules : 
#math (fonctions usuelles, constantes, etc), 
#numpy (fonctions usuelles, constantes, arrays (matrices), etc), 
#mathplotlib (pour les graphiques)
import math as m
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0,2,21)  # tableau avec 21 points équidistants entre 0 et 2
y = np.zeros(21) # tableau avec 21  zeros
print("x =", x)
print(y)
x = m.pi*x
print(x)
y = np.sin(x)
# y= m.sin(x) # la fonction sin du module math ne permet pas d'évaluer un tableau directement
plt.plot(x,y)

x = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604 6.28318531]


Listes et arrays (tableaux)

- on peut créer une liste vide avec nomliste=[] 
- avec x.append() on peut ajouter un nouveau élément à la liste. 
- le i-ème élément de la liste est nomliste[i] (attention, on commence la numérotation à 0)
- len(nomliste) donne la taille de la liste
- avec nomliste.reverse() on inverse l'ordre de la liste 



In [39]:
#Exemple
liste=[]
for i in range(1,11):
    liste.append(1/i)
print(liste)

#le premier élément de la liste : 
print("premier élément = ", liste[0])
#le dernier élément de la liste : 
print("dernier élément = ", liste[9])
# la taille de la liste
print("taille = ", len(liste))

[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1]
premier élément =  1.0
dernier élément =  0.1
taille =  10


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'float'

In [60]:
#Exemple 2 
jours = ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi' ,'samedi', 'dimanche']
print(jours)
print(jours[0:3])
jours.reverse()
print(jours)

['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche']
['lundi', 'mardi', 'mercredi']
['dimanche', 'samedi', 'vendredi', 'jeudi', 'mercredi', 'mardi', 'lundi']


Arrays (tableaux)


- avec nomarray = numpy.zeros(N), on  crée un array nomarray rempli de 𝑁 zeros (donc 𝑁 c'est la taille du tableau) 

- si $0 \le k \le N-1$, alors avec nomarray[k] = V on affecte le  
k-ième élément du tableau avec la valeur V

- nomarray.size donne la taille du tableau.



In [4]:
import numpy #on charge numpy (si ce n'était pas fait avant)
N=10
tableau = numpy.zeros(N)
print(tableau)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
for i in range(0,10):
    tableau[i] = i**2
print(tableau)


[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [24]:
# si on dépasse la taille du tableau, il y a une erreur : 
for i in range(0,11):
    tableau[i] = i**2
print(tableau)


IndexError: index 10 is out of bounds for axis 0 with size 10

In [30]:
tableau2 = numpy.zeros(N)
for i in range(0,10):
    tableau2[i] = (9-i)**2
print(tableau2)

[81. 64. 49. 36. 25. 16.  9.  4.  1.  0.]


In [38]:
# les opérations classiques entre tableaux  sont définies 
somme = tableau + tableau2
print(somme)
produit = tableau * tableau2 # produit des entrées du tableau
print(produit)
racine = tableau**0.5
print(racine)

[81. 65. 53. 45. 41. 41. 45. 53. 65. 81.]
[  0.  64. 196. 324. 400. 400. 324. 196.  64.   0.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Division euclidienne : 
    
- avec a//b on obtient le quotient de la division entière entre les  entiers a et b.

- avec a%b on obtient le reste de la division entre a et b

In [62]:
# Exemple 
q = 143//2
r = 143%2
print('143 = 2*',q,'+',r)


143 = 2* 71 + 1


## Exercice 1

Soit $N$ un nombre entier naturel. L'algorithme suivant calcule la représentation de $N$ en base 2 : 

Initialisation :  $q = N$, Nb2=[]  

tant que $q \neq 0$ faire 

      r  = reste de la division entière de q par 2
      
      q  = quotient de la division entière de q par 2

      Ajouter r dans la liste Nb2

fin tant que

Inverser la liste Nb2

Afficher la liste

On pourra compléter le programme suivant : 

In [2]:
N=input("nombre entier = ")
N=int(N)
q=N;
Nb2 = []
while q != 0:
    r = q%2
    Nb2.append(r) 
    q=q//2
print(Nb2)
Nb2.reverse()
print('N = ',Nb2,'_2')

nombre entier = 9
[1, 0, 0, 1]
N =  [1, 0, 0, 1] _2


## Exercice 2

Soit $f$ un nombre réel dans $[0,1[$. L'algorithme suivant calcule la représentation de $f$ en base 2 (Noter que comme la représentation pourrait avoir une infinité de chiffres après la virgule, on calculera $Nmax$ chiffres : 

$Nmax = 20$

Initialisation :  fn = f, fb2=[], $k = 0$  

tant que fn $\neq 0$ et $k< Nmax$ faire 

      fn  = 2fn
      
      si fn >= 1 alors 
      
          d = 1
          
          fn = fn - 1 
      
      sinon
      
          d = 0
      
      Ajouter d dans la liste fb2
      
      k = k+1

fin tant que

Afficher la liste

On pourra compléter le programme suivant puis le tester avec différentes valeurs de $f$ : 

In [1]:
f=input("nombre decimal = ")
f=float(f)
fn=f
count = 0
fb2 = []
while fn != 0 and count < 20:
    fn=2*fn 
    if fn >= 1 : 
        d = 1
        fn = fn - 1
    else : 
        d = 0
    print('d_',count+1,' = ',d)
    fb2.append(d)
    count += 1
print(fb2)

nombre decimal = 0.4
d_ 1  =  0
d_ 2  =  1
d_ 3  =  1
d_ 4  =  0
d_ 5  =  0
d_ 6  =  1
d_ 7  =  1
d_ 8  =  0
d_ 9  =  0
d_ 10  =  1
d_ 11  =  1
d_ 12  =  0
d_ 13  =  0
d_ 14  =  1
d_ 15  =  1
d_ 16  =  0
d_ 17  =  0
d_ 18  =  1
d_ 19  =  1
d_ 20  =  0
[0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0]


## Exercice 3

En utilisant les programmes des exercice 1 et 2, écrire une fonction python ayant comme argument un nombre $x$ (réel) et qui devra retourner  un tableau composé de $s$, le signe de $x$ ($s=0$ si $x$ est positif ou nul, $s=1$ si $x$ est negatif), du tableau avec la représentation en base $2$ de la partie entière de $|x|$ et du tableau avec la représentation de la partie décimale de $|x|$.

Ind. Pour trouver la partie entière de $x$ on peut utiliser la fonction numpy "floor" : numpy.floor() ou (np.floor() si on a fait "import numpy as np" avant). Attention la réponse est de type float et pas int.

On pourra compléter la fonction suivante : 

In [13]:
import numpy as np

def repbin(x):
    if x >= 0: 
        s=0
    else:
        s=1
    N = np.floor(abs(x))
    f = abs(x)-N
    N=int(N)
    q=N;
    Nb2 = []
    while q != 0:
        r = q%2
        Nb2.append(r) 
        q=q//2
    #print(Nb2)
    Nb2.reverse()
    fn=f
    count = 0
    fb2 = []
    while fn != 0 and count < 20:
        fn=2*fn 
        if fn >= 1 : 
            d = 1
            fn = fn - 1
        else : 
            d = 0
    #    print('d_',count+1,' = ',d)
        fb2.append(d)
        count += 1
    #print(fb2)
    return [s,Nb2,fb2]

In [14]:
repbin(-4.125)

[1, [1, 0, 0], [0, 0, 1]]

In [15]:
repbin(33.126)

[0,
 [1, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]]

In [17]:
R = repbin(31.625)

In [23]:
print("signe : ", R[0])

signe :  0


In [26]:
print("partie entière en base 2 : ", R[1],"_2")

partie entière en base 2 :  [1, 1, 1, 1, 1] _2


In [27]:
print("partie décimale en base 2 : ", R[2],"_2")

partie décimale en base 2 :  [1, 0, 1] _2
